//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McKinsey.PowerPointGenerator.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("McKinsey.PowerPointGenerator.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Name&quot;:&quot;SpendAbsolutesInMn&quot;,&quot;Columns&quot;:[{&quot;Header&quot;:&quot;Labels&quot;,&quot;Data&quot;:[&quot;Total IT&quot;,&quot;Management and overhead&quot;,&quot;Infrastructure&quot;,&quot;Network services&quot;,&quot;Networking&quot;,&quot;Telecoms&quot;,&quot;End user services&quot;,&quot;End user computing&quot;,&quot;Help desk&quot;,&quot;Server infrastructure&quot;,&quot;Data center&quot;,&quot;Other servers&quot;,&quot;ATM infrastructure&quot;,&quot;Applications&quot;,&quot;Application maintenance&quot;,&quot;Application development&quot;]},{&quot;Header&quot;:&quot;#Cl1N#&quot;,&quot;Data&quot;:[1237.152645606154,114.19870574800152,465.06515533214059,54.123184165664249,51.34706435933257,2.7761198063316836,63.766239844 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BigTableTestData {
            get {
                return ResourceManager.GetString("BigTableTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] FullTemplate {
            get {
                object obj = ResourceManager.GetObject("FullTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;ScatterTest&quot;,
        ///  &quot;Columns&quot;: [
        ///    {
        ///      &quot;Header&quot;: &quot;Y-Values&quot;,
        ///      &quot;Data&quot;: [
        ///        9.5,
        ///        8.5,
        ///        8.5,
        ///        7.5,
        ///        6.5,
        ///        6.5,
        ///        5.5,
        ///        4.5,
        ///        3.5,
        ///        2.5
        ///      ]
        ///    },
        ///    {
        ///      &quot;Header&quot;: &quot;Labels&quot;,
        ///      &quot;Data&quot;: [
        ///        &quot;Organization and governance&quot;,
        ///        &quot;HR management&quot;,
        ///        &quot;Project portfolio management&quot;,
        ///        &quot;Demand management capabilities&quot;,
        ///        &quot;Architecture management&quot;,
        ///        &quot;Architecture [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScatterChartData {
            get {
                return ResourceManager.GetString("ScatterChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;SpendByRevenues&quot;,
        ///  &quot;Columns&quot;: [
        ///    {
        ///      &quot;Header&quot;: &quot;#Cl1N#&quot;,
        ///      &quot;Data&quot;: [
        ///        9.5,
        ///        8.5
        ///      ]
        ///    },
        ///    {
        ///      &quot;Header&quot;: &quot;#P1N#&quot;,
        ///      &quot;Data&quot;: [
        ///        8.5,
        ///        7.5
        ///      ]
        ///    },
        ///    {
        ///      &quot;Header&quot;: &quot;#P2N#&quot;,
        ///      &quot;Data&quot;: [
        ///        10.5,
        ///        6.5
        ///      ]
        ///    },
        ///    {
        ///      &quot;Header&quot;: &quot;#P3N#&quot;,
        ///      &quot;Data&quot;: [
        ///        11.5,
        ///        5.5
        ///      ]
        ///    },
        ///    {
        ///      &quot;Header&quot;: &quot;#P4N#&quot;,
        ///      &quot;Data&quot;: [
        ///        12.5,
        ///        4.5
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TableTestData {
            get {
                return ResourceManager.GetString("TableTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p:sp xmlns:p=&quot;http://schemas.openxmlformats.org/presentationml/2006/main&quot;&gt;
        ///  &lt;p:nvSpPr&gt;
        ///    &lt;p:cNvPr id=&quot;8&quot; name=&quot;DATA:customer&quot; /&gt;
        ///    &lt;p:cNvSpPr txBox=&quot;1&quot;&gt;
        ///      &lt;a:spLocks xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; /&gt;
        ///    &lt;/p:cNvSpPr&gt;
        ///    &lt;p:nvPr /&gt;
        ///  &lt;/p:nvSpPr&gt;
        ///  &lt;p:spPr&gt;
        ///    &lt;a:xfrm xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot;&gt;
        ///      &lt;a:off x=&quot;650221&quot; y=&quot;1154369&quot; /&gt;
        ///      &lt;a:ext cx=&quot;4189411&quot; cy=&quot;301367&quot; /&gt;
        ///    &lt;/a:xfrm&gt;
        ///    &lt;a:prstGeom prst=&quot;rect&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestShape {
            get {
                return ResourceManager.GetString("TestShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p:sp xmlns:p=&quot;http://schemas.openxmlformats.org/presentationml/2006/main&quot;&gt;
        ///  &lt;p:nvSpPr&gt;
        ///    &lt;p:cNvPr id=&quot;9&quot; name=&quot;DATA:customer&quot; /&gt;
        ///    &lt;p:cNvSpPr txBox=&quot;1&quot;&gt;
        ///      &lt;a:spLocks xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; /&gt;
        ///    &lt;/p:cNvSpPr&gt;
        ///    &lt;p:nvPr /&gt;
        ///  &lt;/p:nvSpPr&gt;
        ///  &lt;p:spPr&gt;
        ///    &lt;a:xfrm xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot;&gt;
        ///      &lt;a:off x=&quot;650221&quot; y=&quot;1763969&quot; /&gt;
        ///      &lt;a:ext cx=&quot;4189411&quot; cy=&quot;301367&quot; /&gt;
        ///    &lt;/a:xfrm&gt;
        ///    &lt;a:prstGeom prst=&quot;rect&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestShapeWithTag {
            get {
                return ResourceManager.GetString("TestShapeWithTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ThreeSlides {
            get {
                object obj = ResourceManager.GetObject("ThreeSlides", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
